name: Diary Auto-Update
on:
  issues:
    types: [opened]

jobs:
  update-diary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install markdown beautifulsoup4
      - name: Process entry
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python .github/scripts/process.py "${{ github.event.issue.title }}" "${{ github.event.issue.body }}" 
          git config --global user.name "Diary Bot"
          git config --global user.email "actions@diary.com"
          git add thoughts.html
          git commit -m "Добавлена запись: ${{ github.event.issue.title }}"
          git push
